export enum ConveyanceEnum {
    METRO = "METRO",
    AUTO = "AUTO",
    CAMIONETA = "CAMIONETA",
    MOTOCICLETA = "MOTOCICLETA",
    TRANSANTIAGO="TRANSANTIAGO",
    BUS =  "BUS",
    AVION_CHILE="AVION_CHILE",
    AVION_INTERNACIONAL="AVION_INTERNACIONAL",
    CAMINANDO = "CAMINANDO"
}